name: Feature request
description: Suggest an idea for this project
labels: enhancement,needs-triage

body:
- type: markdown
  attributes:
    value: Please **do not use** external websites (such as drop box or google drive) to upload screenshots, save files etc. External links have a tendency to become dead. Upload the files to github insted by using one of the below fields.
- type: textarea
  attributes:
    label: Describe the feature
  validations:
    required: true
