message(STATUS "Build for Windows system")

set(PLATFORM_WINDOWS 1)
set(PLATFORM_GNU     0)
set(PLATFORM_LINUX   0)
set(PLATFORM_MACOSX  0)
set(PLATFORM_FREEBSD 0)
set(PLATFORM_OTHER   0)

set(PLATFORM_INSTALL_BIN_DIR "")
set(PLATFORM_INSTALL_LIB_DIR "")
set(PLATFORM_INSTALL_DATA_DIR "data")
set(PLATFORM_INSTALL_I18N_DIR "lang")
set(PLATFORM_INSTALL_DOC_DIR "doc")
