# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "OFF")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "OFF")
SET(CPACK_BINARY_NSIS "ON")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_PRODUCTBUILD "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "OFF")
SET(CPACK_BINARY_ZIP "OFF")
SET(CPACK_BUILD_SOURCE_DIRS "C:/Users/Fiftytwo/Repos/colobot;C:/Users/Fiftytwo/Repos/colobot/src")
SET(CPACK_BUNDLE_NAME "Colobot: Gold Edition")
SET(CPACK_CMAKE_GENERATOR "MSYS Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "NSIS")
SET(CPACK_INSTALL_CMAKE_PROJECTS "C:/Users/Fiftytwo/Repos/colobot/src;colobot;ALL;/")
SET(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/colobot")
SET(CPACK_MODULE_PATH "C:/Users/Fiftytwo/Repos/colobot/cmake")
SET(CPACK_NSIS_DEFINES "SetOverwrite on
BrandingText \"Colobot: Gold Edition (0.1.11+alpha-git-dev~radda8281)\"")
SET(CPACK_NSIS_DISPLAY_NAME "Colobot")
SET(CPACK_NSIS_EXECUTABLES_DIRECTORY ".")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "!define MUI_HEADERIMAGE_BITMAP       \"C:/Users/Fiftytwo/Repos/colobot/desktop/colobot_nsis.bmp\"
                                           !define MUI_WELCOMEFINISHPAGE_BITMAP \"C:/Users/Fiftytwo/Repos/colobot/desktop/colobot_nsis_left.bmp\"")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
SET(CPACK_NSIS_MUI_FINISHPAGE_RUN "colobot.exe")
SET(CPACK_NSIS_MUI_ICON "C:/Users/Fiftytwo/Repos/colobot/desktop/colobot.ico")
SET(CPACK_NSIS_MUI_UNIICON "C:/Users/Fiftytwo/Repos/colobot/desktop/colobot.ico")
SET(CPACK_NSIS_PACKAGE_NAME "Colobot")
SET(CPACK_OUTPUT_CONFIG_FILE "C:/Users/Fiftytwo/Repos/colobot/src/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Users/Fiftytwo/Repos/colobot/desktop/../README.md")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Colobot: Gold Edition")
SET(CPACK_PACKAGE_EXECUTABLES "colobot;Colobot: Gold Edition")
SET(CPACK_PACKAGE_FILE_NAME "colobot-0.1.11+alpha-git-dev~radda8281")
SET(CPACK_PACKAGE_ICON "")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "Colobot")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Colobot")
SET(CPACK_PACKAGE_NAME "colobot")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "TerranovaTeam")
SET(CPACK_PACKAGE_VERSION "0.1.11")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "11")
SET(CPACK_RESOURCE_FILE_LICENSE "C:/Users/Fiftytwo/Repos/colobot/desktop/../LICENSE.txt")
SET(CPACK_RESOURCE_FILE_README "C:/msys64/mingw64/share/cmake-3.9/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "C:/msys64/mingw64/share/cmake-3.9/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "ON")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "7Z;ZIP")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/Fiftytwo/Repos/colobot/src/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_RPM "")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TXZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "ON")
SET(CPACK_STRIP_FILES "TRUE")
SET(CPACK_SYSTEM_NAME "win64")
SET(CPACK_TOPLEVEL_TAG "win64")
SET(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/Fiftytwo/Repos/colobot/src/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
